export const ActionTypes = {
  GET_REPOS_NAME     : 'GET_REPOS_NAME',
  GET_GITHUB_REPOS   : 'GET_GITHUB_REPOS',
  GET_LANGUAGE_URL   : 'GET_LANGUAGE_URL',
  SET_LANGUAGE       : 'SET_LANGUAGE',
  SET_SPECIFIC_REPOS : 'SET_SPECIFIC_REPOS'
}

